#Excercise 5, Intro to Rec. Sys.
***Author: Seyedeh Sharareh Mirzargar***

In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
movie_vector_representation_to_recommend = pd.read_csv('movie-vector-representation_to_recommend.csv', header=0)
movie_vector_representation_to_recommend

    Id Number  ... Contains Wetstern
0           1  ...                 0
1           2  ...                 0
2           3  ...                 0
3           4  ...                 0
4           5  ...                 0
5           6  ...                 0
6           7  ...                 0
7           8  ...                 0
8           9  ...                 0
9          10  ...                 0
10         11  ...                 0
11         12  ...                 0
12         13  ...                 0
13         14  ...                 0
14         15  ...                 0

[15 rows x 20 columns]

In [3]:
movie_vector_representation_rated = pd.read_csv('movie-vector-representation_rated.csv', header=0)
movie_vector_representation_rated

    Id Number  ... Contains Wetstern
0           0  ...                 0
1           1  ...                 0
2           2  ...                 0
3           3  ...                 0
4           4  ...                 0
5           5  ...                 0
6           6  ...                 0
7           7  ...                 0
8           8  ...                 0
9           9  ...                 0
10         10  ...                 0
11         11  ...                 0
12         12  ...                 0
13         13  ...                 0
14         14  ...                 0
15         15  ...                 0
16         16  ...                 0
17         17  ...                 0
18         18  ...                 0
19         19  ...                 0
20         20  ...                 0
21         21  ...                 0
22         22  ...                 0
23         23  ...                 0
24         24  ...                 0
25         25  ...                 0
26         26  ...                 0
27         27  ...                 0
28         28  ...                 0
29         29  ...                 0
30         30  ...                 0
31         31  ...                 0
32         32  ...                 0
33         33  ...                 0
34         34  ...                 0
35         35  ...                 0
36         36  ...                 0
37         37  ...                 0
38         38  ...                 0
39         39  ...                 0
40         40  ...                 0
41         41  ...                 0
42         42  ...                 0
43         43  ...                 0
44         44  ...                 0
45         45  ...                 0
46         46  ...                 0
47         47  ...                 0
48         48  ...                 0
49         49  ...                 0

[50 rows x 20 columns]

In [4]:
similarities = pd.read_csv('similarities.csv', header=0)
similarities

                                     Dark Knight, The  ...  similarity.49
0                                         10,000 B.C.  ...          0.816
1                                  Burn After Reading  ...          0.816
2                                Incredible Hulk, The  ...          0.577
3   Indiana Jones and the Kingdom of the Crystal S...  ...          0.577
4                                       Kung Fu Panda  ...          0.577
5                                   Quantum of Solace  ...          0.408
6                                      Tropic Thunder  ...          0.333
7                                              Jumper  ...          0.333
8                         HellBoy II: The Golden Army  ...          0.289
9                           Forgetting Sarah Marshall  ...          0.258
10                                          Get Smart  ...          0.000
11                                   Sex and the City  ...          0.000
12                                     Be Kind Rewind  ...          0.000
13                      You Don't Mess with the Zohan  ...          0.000
14          Chronicles of Narnia: Prince Caspian, The  ...          0.000

[15 rows x 100 columns]

In [5]:
user_movie_ratings = pd.read_csv('user_movie_ratings.csv', header=0)
user_movie_ratings

    ID                                              Movie  ...       U57       U58
0    0                                   Dark Knight, The  ...  3.861111  5.000000
1    1     Lord of the Rings: The Return of the King, The  ...  3.500000  4.000000
2    2                              Bourne Ultimatum, The  ...  3.687500  4.500000
3    3                                              WALLE  ...  3.790323  3.790323
4    4                                       Finding Nemo  ...  4.000000  3.500000
5    5                                   Incredibles, The  ...  4.000000  4.000000
6    6                                        Ratatouille  ...  3.294118  2.000000
7    7                                     Monsters, Inc.  ...  3.904255  2.500000
8    8                                              Shrek  ...  3.500000  4.500000
9    9                                   Schindler's List  ...  4.528571  5.000000
10  10                       There's Something About Mary  ...  2.840000  4.500000
11  11  Pirates of the Caribbean: The Curse of the Bla...  ...  4.500000  4.000000
12  12                         Other Side of the Bed, The  ...  3.137500  3.137500
13  13                                       Pulp Fiction  ...  3.972973  5.000000
14  14                                           Sin City  ...  3.611111  5.000000
15  15                              Bowling for Columbine  ...  4.065217  4.065217
16  16                                      Super Size Me  ...  4.500000  3.733333
17  17                                        City of God  ...  4.111111  4.111111
18  18                                    Pan's Labyrinth  ...  3.418919  3.418919
19  19       Star Wars: Episode III - Revenge of the Sith  ...  3.523810  3.500000
20  20                                     Fantastic Four  ...  2.906250  2.000000
21  21                            Exorcist: The Beginning  ...  2.854167  1.500000
22  22                                              Seven  ...  4.238095  4.500000
23  23                                          Game, The  ...  3.711538  4.500000
24  24                                       Pretty Woman  ...  4.500000  2.500000
25  25                                        Matrix, The  ...  3.682692  5.000000
26  26                         Terminator 2: Judgment Day  ...  3.297297  5.000000
27  27                                              X-Men  ...  3.536585  3.000000
28  28                                   Sixth Sense, The  ...  3.520000  4.000000
29  29                            Mission: Impossible III  ...  2.265625  4.000000
30  30                                                300  ...  4.500000  5.000000
31  31                                               Troy  ...  4.500000  2.500000
32  32                                       Transformers  ...  2.903846  3.500000
33  33                             No Country for Old Men  ...  3.269231  4.000000
34  34                                    Sea Inside, The  ...  3.534483  3.534483
35  35                                       Pianist, The  ...  4.212121  4.500000
36  36                                Million Dollar Baby  ...  3.828571  5.000000
37  37                                     Orphanage, The  ...  3.439394  3.439394
38  38                                            Titanic  ...  3.509259  4.500000
39  39                          Silence of the Lambs, The  ...  4.130952  5.000000
40  40                                 Brokeback Mountain  ...  3.224138  3.224138
41  41                                              [Rec]  ...  3.089286  3.089286
42  42                                             Volver  ...  2.788462  2.788462
43  43     Sweeney Todd: The Demon Barber of Fleet Street  ...  3.717391  3.717391
44  44                                         Changeling  ...  3.727273  3.727273
45  45                               English Patient, The  ...  3.460000  4.000000
46  46                                       Hotel Rwanda  ...  4.184211  4.500000
47  47                                High School Musical  ...  2.352941  2.352941
48  48                                    Fahrenheit 9/11  ...  3.868421  3.868421
49  49                                         Mamma Mia!  ...  3.575000  3.575000

[50 rows x 61 columns]

In [6]:
rated_movies = list(user_movie_ratings['Movie'])
num_rated_movies = len(rated_movies)

I chose the groups 1 and 2 and 3

In [7]:
groups_rec={'Group 1':{},'Group 2':{},'Group 3':{}}
groups={'Group 1':[10,26,30,12,11,16,37,29,36],'Group 2':[2,3,28,44,41],'Group 3':[11,15,29]}
groups

{'Group 1': [10, 26, 30, 12, 11, 16, 37, 29, 36],
 'Group 2': [2, 3, 28, 44, 41],
 'Group 3': [11, 15, 29]}

I chose to use the following stategies:


*   Average
*   Multiplicative
*   Most pleasure
*   least misery 
*   Average without misery

In [8]:
def collect_rating(users_id,user_movie_ratings,rated_movies):
  #for each movie in the list of the rated_movies:
  users_rating=[]

  for movie_idx in range(len(rated_movies)):
    users_rating.append([])
  #iterate over the memberd of the group
    for id in users_id:
      user = "U"+str(id)
      users_rating[movie_idx].append(user_movie_ratings.iloc[movie_idx][user])
  return users_rating

In [9]:
def average_strategy(users_rating,num_rated_movies):
  average_ratings = []
  for movie in range(num_rated_movies):
    average_ratings.append(np.mean(np.array(users_rating[movie])))
  return np.array(average_ratings)

In [10]:
def multiplicative_strategy(users_rating,num_rated_movies):
  multiplicative_ratings = []
  for movie in range(num_rated_movies):
    multiplicative_ratings.append(np.prod(users_rating[movie]))
  return np.array(multiplicative_ratings)

In [11]:
def most_pleasure_strategy(users_rating,num_rated_movies):
  most_pleasure_ratings = []
  for movie in range(num_rated_movies):
    most_pleasure_ratings.append(np.max(np.array(users_rating[movie])))
  return np.array(most_pleasure_ratings)

In [12]:
def least_misery_strategy(users_rating,num_rated_movies):
  least_misery_ratings = []
  for movie in range(num_rated_movies):
    least_misery_ratings.append(np.min(np.array(users_rating[movie])))
  return np.array(least_misery_ratings)

In [13]:
def average_without_misery_strategy(users_rating,num_rated_movies):
  average_without_misery_ratings = []
  for movie in range(num_rated_movies):
    tmp = np.array(users_rating[movie])
    min = np.min(tmp)
    sum = 0
    for t in tmp:
      if(t!=min):
        sum += t
    average_without_misery_ratings.append(sum/(len(tmp)-1))
  return np.array(average_without_misery_ratings)

In [14]:
for key,value in groups.items():
  ratings = {}
  users_rating = collect_rating(value,user_movie_ratings,rated_movies)
  ratings['average'] = average_strategy(users_rating,num_rated_movies)
  ratings['multiplicative'] = multiplicative_strategy(users_rating,num_rated_movies)
  ratings ['most pleasure'] = most_pleasure_strategy(users_rating,num_rated_movies)
  ratings ['least misery strategy'] = least_misery_strategy(users_rating,num_rated_movies)
  ratings ['average without misery'] = average_without_misery_strategy(users_rating,num_rated_movies)
  top_ten_movies_index = {}
  for k,v in ratings.items():
    top_ten_movies_index [k] = v.argsort()[-10:][::-1]
  print(top_ten_movies_index)
  movies_to_rec = {}
  for k,v in top_ten_movies_index.items():
    tmp = []
    selected_movie = None
    iter = 0
    while(len(tmp)<3):
        #select the most similar movie
        selected_movie = similarities.iloc[0][rated_movies[v[iter]]]
        #if our list is not empty, check for duplications
        
        if(len(tmp)>0 and tmp.count(selected_movie)>0):
          selected_movie = None
        else:
          tmp.append(selected_movie)
        iter+=1
    
    movies_to_rec[k]=tmp
  
  groups_rec[key] = movies_to_rec

{'average': array([22,  3,  9,  8, 39, 25, 35,  2, 46,  0]), 'multiplicative': array([22,  3, 39,  8, 35,  9, 25,  0,  2, 46]), 'most pleasure': array([24, 34, 18, 19, 20, 22, 48, 25, 26, 11]), 'least misery strategy': array([ 0, 22, 35, 36, 19,  3,  2, 46, 45, 28]), 'average without misery': array([ 9,  8, 22,  3, 39, 25, 15,  2,  4, 43])}
{'average': array([ 9, 39, 35, 22, 38,  8, 17,  7, 36, 46]), 'multiplicative': array([ 9, 39, 35,  8, 38, 22, 17,  7, 46, 36]), 'most pleasure': array([49, 37, 14, 22, 30,  9,  8, 17, 34, 35]), 'least misery strategy': array([ 9, 35, 17, 15, 46, 39, 38,  8, 13,  7]), 'average without misery': array([39,  9, 22, 36, 46, 30, 37, 23,  5, 40])}
{'average': array([ 3, 19,  9,  2,  8, 25,  4,  7, 11, 15]), 'multiplicative': array([ 3, 19,  9,  2,  8, 25, 15,  7, 11,  4]), 'most pleasure': array([49, 41, 22, 19, 15, 11,  7,  8,  4,  3]), 'least misery strategy': array([ 9,  3, 19,  2, 25, 18, 17, 15, 13,  0]), 'average without misery': array([19,  4,  8, 49,  7, 11, 41,  2,  1, 22])}

In [15]:
groups_rec

{'Group 1': {'average': ['Burn After Reading',
   'Forgetting Sarah Marshall',
   '10,000 B.C.'],
  'average without misery': ['10,000 B.C.',
   'Forgetting Sarah Marshall',
   'Burn After Reading'],
  'least misery strategy': ['10,000 B.C.',
   'Burn After Reading',
   'HellBoy II: The Golden Army'],
  'most pleasure': ['Forgetting Sarah Marshall', '10,000 B.C.', 'Jumper'],
  'multiplicative': ['Burn After Reading',
   'Forgetting Sarah Marshall',
   '10,000 B.C.']},
 'Group 2': {'average': ['10,000 B.C.',
   'Burn After Reading',
   'Forgetting Sarah Marshall'],
  'average without misery': ['Burn After Reading',
   '10,000 B.C.',
   'Incredible Hulk, The'],
  'least misery strategy': ['10,000 B.C.',
   'Incredible Hulk, The',
   'Burn After Reading'],
  'most pleasure': ['Forgetting Sarah Marshall',
   'Jumper',
   'Quantum of Solace'],
  'multiplicative': ['10,000 B.C.',
   'Burn After Reading',
   'Forgetting Sarah Marshall']},
 'Group 3': {'average': ['Forgetting Sarah Marshall',
   'HellBoy II: The Golden Army',
   '10,000 B.C.'],
  'average without misery': ['HellBoy II: The Golden Army',
   'Indiana Jones and the Kingdom of the Crystal Skull',
   'Forgetting Sarah Marshall'],
  'least misery strategy': ['10,000 B.C.',
   'Forgetting Sarah Marshall',
   'HellBoy II: The Golden Army'],
  'most pleasure': ['Forgetting Sarah Marshall',
   'Quantum of Solace',
   'Burn After Reading'],
  'multiplicative': ['Forgetting Sarah Marshall',
   'HellBoy II: The Golden Army',
   '10,000 B.C.']}}

In [16]:
pd.concat({k: pd.DataFrame(v).T for k, v in groups_rec.items()}, axis=0)

                                                          0  ...                            2
Group 1 average                          Burn After Reading  ...                  10,000 B.C.
        multiplicative                   Burn After Reading  ...                  10,000 B.C.
        most pleasure             Forgetting Sarah Marshall  ...                       Jumper
        least misery strategy                   10,000 B.C.  ...  HellBoy II: The Golden Army
        average without misery                  10,000 B.C.  ...           Burn After Reading
Group 2 average                                 10,000 B.C.  ...    Forgetting Sarah Marshall
        multiplicative                          10,000 B.C.  ...    Forgetting Sarah Marshall
        most pleasure             Forgetting Sarah Marshall  ...            Quantum of Solace
        least misery strategy                   10,000 B.C.  ...           Burn After Reading
        average without misery           Burn After Reading  ...         Incredible Hulk, The
Group 3 average                   Forgetting Sarah Marshall  ...                  10,000 B.C.
        multiplicative            Forgetting Sarah Marshall  ...                  10,000 B.C.
        most pleasure             Forgetting Sarah Marshall  ...           Burn After Reading
        least misery strategy                   10,000 B.C.  ...  HellBoy II: The Golden Army
        average without misery  HellBoy II: The Golden Army  ...    Forgetting Sarah Marshall

[15 rows x 3 columns]

#Questions
1.   Are there any differences between the recommendation lists that you obtained? Why are
those changes? which one do you think is better?

>>*Answer:*There are some minor differences between the recommnedations, such as the order of the recommendations. These differences are because of that each strategy tries to improve a specific goal. For example, the least misery strategy tries to improve the worst-case expreience while the average without misery tries to alleviate the effect of worst ratings on the outcome of the group rating. I beilve, there is no ' the best' strategy because deponding on the context and target audience, each of these strategies might work well.

2.   The groups participated in a real experiment. The decisions they made are presented in
Table 3, you can find the names of the movies corresponding to each ID in the sheet Movies
Vector Representation (Movies to Recommend). Are these results different from the ones you obtained? What do you think are the reasons for
that? Which advantages and disadvantages can you identify from the different aggregation
strategies? 

>>*Answer:* 
I would like to first of all that the example for 'least misery' strategy has been solved for a group of {2,3,38,41,44} while the given group is {2,3,28,41,44} and it affects the results.
I focus on the 1st, 2nd, and 3rd group in this assignment and this means that in practice; there groups have chosen to watch the:
* Group 1: 1-Kung Fu Panda 2-Indiana Jones and the Kingdom of the Crystal Skull 3- Be Kind Rewind
*  Group 2: 1-Sex and the City 2-Kung Fu Panda 3-Forgetting Sarah Marshall
*  Group 3: 1-Indiana Jones and the Kingdom of the Crystal Skull 2-Kung Fu Panda 3-Sex and the City

Are these results different from the ones you obtained? What do you think are the reasons for
that? 

>>*Answer:* Yes, the results are different. For group1, there is no overlap between the recommendations and the ground truth. For group2, 'Forget Sarah Marshal' is shared between the ground truth and the recommendations. Finally, for group 3, 'Indiana Jones and the Kingdom of the Crystal ..' is shared. One possible explanation would be that the decision of a group involvesa set of multiple rules (minimizing the worst case experience, alleviating least score, overall satisfaction,...) while our strategies consider only one of these metrics at a time. Another possible explanation would be that there are other parameters involved. For example, all the memebers might have seen advertisement of a movie and agree to see it together, while based on the features of the movie, it is not among the top-3 recommended movies.

Which advantages and disadvantages can you identify from the different aggregation strategies?

>> Different strategies, try to improve the recommendations absed on their opbjective and deponding on the given application, we can take advantage of their specific target (an example: alleviating the impact of the least ranking in competitive applications). However, the table3 shows that these strategies have their own disadvantages and they might produce recommendations that are weak overall, because the strategy is designed for a very specific target. For example, while the 'average strategy' tries to provide a simple approach to provide recommendations that are suitbale for overall taste ofthe group, it might produce recommendations that are far from the ground truth because in practice, rarely people converge to the average because of other parameters (for example, while the average taste of a community is romantic movies, a small group of critics, always bias the outcome of the community to movies that are delicate and feature-rich)